// <auto-generated />
using System;
using JadeWesserPort.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JadeWesserPort.Data.Migrations.PostgresMigrations
{
    [DbContext(typeof(JWPDbContext))]
    partial class JWPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CrewMemberVesselVisitNotification", b =>
                {
                    b.Property<Guid>("CrewManifestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("inVesselVisitsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CrewManifestId", "inVesselVisitsId");

                    b.HasIndex("inVesselVisitsId");

                    b.ToTable("CrewMemberVesselVisitNotification");
                });

            modelBuilder.Entity("DockRecordVesselType", b =>
                {
                    b.Property<Guid>("AllowedVesselTypesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocksId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedVesselTypesId", "DocksId");

                    b.HasIndex("DocksId");

                    b.ToTable("DockRecordVesselType");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CargoManifestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerISO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CargoManifestId");

                    b.ToTable("CargoItems");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CargoType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CargoManifests");

                    b.HasDiscriminator().HasValue("CargoManifest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CrewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CitizenshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CrewMember");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.DockRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Depth")
                        .HasColumnType("REAL");

                    b.Property<float>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("MaxDraft")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StorageAreaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StorageAreaId");

                    b.ToTable("DockRecords");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.DockStorageDistance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DockRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageAreaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockRecordId");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("DockStorageDistances");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlphanumericCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("SetupTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlphanumericCode")
                        .IsUnique();

                    b.ToTable("Resources");

                    b.HasDiscriminator().HasValue("Resource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.ShippingAgentRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("ShippingAgentRepresentatives");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvailableSince")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvailableUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerISO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageAreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerISO")
                        .IsUnique();

                    b.HasIndex("StorageAreaId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.StorageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.VVNFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Imo")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.VesselType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Draft")
                        .HasColumnType("REAL");

                    b.Property<float>("Length")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxBays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.VesselVisitNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CargoLoadManifestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CargoUnloadManifestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Etd")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FeedBackId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingAgentRepresentativeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CargoLoadManifestId")
                        .IsUnique();

                    b.HasIndex("CargoUnloadManifestId")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DockId");

                    b.HasIndex("FeedBackId");

                    b.HasIndex("ShippingAgentRepresentativeId");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotifications");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.OperationalWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("OperationalWindows");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.PrivacyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("PrivacyPolicies");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MecanographicNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("MecanographicNumber");

                    b.HasIndex("MecanographicNumber")
                        .IsUnique();

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.System.DataRectificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedFields")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataRectificationRequests");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.System.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivationExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth0Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasReadPrivacyPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QualificationResource", b =>
                {
                    b.Property<Guid>("QualificationsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourcesId")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationsId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("QualificationResource");
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.Property<Guid>("QualificationsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffMembersId")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationsId", "StaffMembersId");

                    b.HasIndex("StaffMembersId");

                    b.ToTable("QualificationStaffMember");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoManifests.CargoLoadManifest", b =>
                {
                    b.HasBaseType("JadeWesserPort.Domain.Entities.CargoManifest");

                    b.HasDiscriminator().HasValue("CargoLoadManifest");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoManifests.CargoUnloadManifest", b =>
                {
                    b.HasBaseType("JadeWesserPort.Domain.Entities.CargoManifest");

                    b.HasDiscriminator().HasValue("CargoUnloadManifest");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resources.STSCrane", b =>
                {
                    b.HasBaseType("JadeWesserPort.Domain.Entities.Resource");

                    b.Property<Guid?>("DockRecordId")
                        .HasColumnType("TEXT");

                    b.HasIndex("DockRecordId");

                    b.HasDiscriminator().HasValue("STSCrane");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resources.TerminalTruck", b =>
                {
                    b.HasBaseType("JadeWesserPort.Domain.Entities.Resource");

                    b.HasDiscriminator().HasValue("TerminalTruck");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resources.YardCrane", b =>
                {
                    b.HasBaseType("JadeWesserPort.Domain.Entities.Resource");

                    b.Property<Guid?>("StorageAreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StotageAreaId")
                        .HasColumnType("TEXT");

                    b.HasIndex("StorageAreaId");

                    b.HasDiscriminator().HasValue("YardCrane");
                });

            modelBuilder.Entity("CrewMemberVesselVisitNotification", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.CrewMember", null)
                        .WithMany()
                        .HasForeignKey("CrewManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.VesselVisitNotification", null)
                        .WithMany()
                        .HasForeignKey("inVesselVisitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DockRecordVesselType", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.VesselType", null)
                        .WithMany()
                        .HasForeignKey("AllowedVesselTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.DockRecord", null)
                        .WithMany()
                        .HasForeignKey("DocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoItem", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.CargoManifest", null)
                        .WithMany("CargoItems")
                        .HasForeignKey("CargoManifestId");

                    b.OwnsOne("JadeWesserPort.Domain.Entities.ValueObjects.ContainerPosition", "VesselContainerPosition", b1 =>
                        {
                            b1.Property<Guid>("CargoItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bay")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Row")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Tier")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CargoItemId");

                            b1.ToTable("CargoItems");

                            b1.WithOwner()
                                .HasForeignKey("CargoItemId");
                        });

                    b.Navigation("VesselContainerPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.DockRecord", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.StorageArea", null)
                        .WithMany("Docks")
                        .HasForeignKey("StorageAreaId");

                    b.OwnsOne("Vector3D", "Position3D", b1 =>
                        {
                            b1.Property<Guid>("DockRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("DockRecordId");

                            b1.ToTable("DockRecords");

                            b1.WithOwner()
                                .HasForeignKey("DockRecordId");
                        });

                    b.OwnsOne("Size3D", "Size3D", b1 =>
                        {
                            b1.Property<Guid>("DockRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Depth")
                                .HasColumnType("REAL");

                            b1.Property<float>("Height")
                                .HasColumnType("REAL");

                            b1.Property<float>("Width")
                                .HasColumnType("REAL");

                            b1.HasKey("DockRecordId");

                            b1.ToTable("DockRecords");

                            b1.WithOwner()
                                .HasForeignKey("DockRecordId");
                        });

                    b.Navigation("Position3D")
                        .IsRequired();

                    b.Navigation("Size3D")
                        .IsRequired();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.DockStorageDistance", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.DockRecord", "DockRecord")
                        .WithMany()
                        .HasForeignKey("DockRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.StorageArea", "StorageArea")
                        .WithMany()
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockRecord");

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.Company", "Company")
                        .WithMany("Representatives")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.System.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.StorageArea", "StorageArea")
                        .WithMany("StockItems")
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.StorageArea", b =>
                {
                    b.OwnsOne("Vector3D", "Position3D", b1 =>
                        {
                            b1.Property<Guid>("StorageAreaId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.OwnsOne("Size3D", "Size3D", b1 =>
                        {
                            b1.Property<Guid>("StorageAreaId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Depth")
                                .HasColumnType("REAL");

                            b1.Property<float>("Height")
                                .HasColumnType("REAL");

                            b1.Property<float>("Width")
                                .HasColumnType("REAL");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("Position3D")
                        .IsRequired();

                    b.Navigation("Size3D")
                        .IsRequired();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Vessel", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.Company", "Operator")
                        .WithMany("OperatedVessels")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.Company", "Owner")
                        .WithMany("OwnedVessels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.VesselType", "Type")
                        .WithMany("Vessels")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Owner");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.VesselVisitNotification", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.CargoManifests.CargoLoadManifest", "CargoLoadManifest")
                        .WithOne("VVN")
                        .HasForeignKey("JadeWesserPort.Domain.Entities.VesselVisitNotification", "CargoLoadManifestId");

                    b.HasOne("JadeWesserPort.Domain.Entities.CargoManifests.CargoUnloadManifest", "CargoUnloadManifest")
                        .WithOne("VVN")
                        .HasForeignKey("JadeWesserPort.Domain.Entities.VesselVisitNotification", "CargoUnloadManifestId");

                    b.HasOne("JadeWesserPort.Domain.Entities.DockRecord", "Dock")
                        .WithMany("Visits")
                        .HasForeignKey("DockId");

                    b.HasOne("JadeWesserPort.Domain.Entities.VVNFeedback", "FeedBack")
                        .WithMany()
                        .HasForeignKey("FeedBackId");

                    b.HasOne("JadeWesserPort.Domain.Entities.ShippingAgentRepresentative", "ShippingAgentRepresentative")
                        .WithMany("VesselVisitNotifications")
                        .HasForeignKey("ShippingAgentRepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoLoadManifest");

                    b.Navigation("CargoUnloadManifest");

                    b.Navigation("Dock");

                    b.Navigation("FeedBack");

                    b.Navigation("ShippingAgentRepresentative");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.OperationalWindow", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.StaffMember", "StaffMember")
                        .WithMany("OperationalWindows")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Shift", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.Resource", "Resource")
                        .WithMany("Shifts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.StaffMember", "StaffMember")
                        .WithMany("Shifts")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("QualificationResource", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JadeWesserPort.Domain.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resources.STSCrane", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.DockRecord", "DockRecord")
                        .WithMany("STSCranes")
                        .HasForeignKey("DockRecordId");

                    b.Navigation("DockRecord");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resources.YardCrane", b =>
                {
                    b.HasOne("JadeWesserPort.Domain.Entities.StorageArea", "StorageArea")
                        .WithMany("YardCranes")
                        .HasForeignKey("StorageAreaId");

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoManifest", b =>
                {
                    b.Navigation("CargoItems");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Company", b =>
                {
                    b.Navigation("OperatedVessels");

                    b.Navigation("OwnedVessels");

                    b.Navigation("Representatives");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.DockRecord", b =>
                {
                    b.Navigation("STSCranes");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.Resource", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.ShippingAgentRepresentative", b =>
                {
                    b.Navigation("VesselVisitNotifications");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.StorageArea", b =>
                {
                    b.Navigation("Docks");

                    b.Navigation("StockItems");

                    b.Navigation("YardCranes");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.VesselType", b =>
                {
                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.StaffMember", b =>
                {
                    b.Navigation("OperationalWindows");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoManifests.CargoLoadManifest", b =>
                {
                    b.Navigation("VVN")
                        .IsRequired();
                });

            modelBuilder.Entity("JadeWesserPort.Domain.Entities.CargoManifests.CargoUnloadManifest", b =>
                {
                    b.Navigation("VVN")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
